### PR TITLE
[DO NOT MERGE]Chinese Pig Year

### PR DESCRIPTION
**Pull request by billchenchina**
Do not merge until https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190205T0000&p1=33&ah=3

### CODE REVIEW

**Comment by asgrim** [comment]
It's very likely I will forget to merge this, perfect! Thanks for contributing!

**Comment by qwIvan** [comment]
Should use London time instead of Beijing time.
应该使用伦敦时间而不是北京时间。

**Comment by ZeroAurora** [comment]
Ok, it's time to merge.

**Comment by asgrim** [comment]
Thanks for the ping!

**Pull request merged**
